export const CHANGE_APP_THEME = 'CHANGE_APP_THEME';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';

export const GET_USER_ALL_TASK = 'GET_USER_ALL_TASK';
export const GET_USER_ALL_LOADING = 'GET_USER_ALL_LOADING';
export const GET_USER_ALL_ERROR = 'GET_USER_ALL_ERROR';

export const TOGGLE_TASK = 'TOGGLE_TASK';

export const USER_EMAIL_LINK = 'USER_EMAIL_LINK';